services:
  cpu:
    build:
      context: .
      args:
        DEVICE: cpu
        TORCH_DTYPE: float32
      tags:
        - gperdrizet/stegosaurus:${VERSION:-dev}-cpu
        - gperdrizet/stegosaurus:latest-cpu
    image: gperdrizet/stegosaurus:${VERSION:-dev}-cpu
    ports:
      - "8080:8080"

  gpu:
    build:
      context: .
      args:
        DEVICE: gpu
        TORCH_DTYPE: bfloat16
      tags:
        - gperdrizet/stegosaurus:${VERSION:-dev}-gpu
        - gperdrizet/stegosaurus:latest-gpu
    image: gperdrizet/stegosaurus:${VERSION:-dev}-gpu
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
